#!/usr/bin/python

legitImput = False
while not legitImput:
    try:
        number = int(raw_input("Enter your starting number: "));
        #number = int(usernumber)
    except ValueError as e:
        print(e)
        print("Try again")
    else:
        legitImput = True

while number != 1:
    if number % 3 == 0:
        number = number / 3
        print number;
    elif number % 3 == 1:
        print(number, "- 1")
        number = number - 1
    elif number % 3 == 2:
        print(number, "+ 1")
        number = number + 1